version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-production:
        dependency-type: production
      rust-development:
        dependency-type: development

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      android-production:
        dependency-type: production
      android-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
