name: Main snapshot release

on:
  pull_request:
    paths:
      - '.github/workflows/main-snapshot-release.yml'
  push:
    branches:
      - main

jobs:
  validate-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
